-- 0094: 장르 검색 — 공포/공겜/공포겜/호러 → 공포 게임을 한 방송, 코옵·오픈월드·RPG·FPS·리듬·퍼즐… 전부.
--
-- 소유자(2026-09-18): "공포라고 하면 공겜도 같이 검색되거나 연관검색어에 나와야 하고, 그 게임이 공포 태그면
-- 그 게임을 한 다시보기도 검색돼야 한다. RPG·코옵·오픈월드 등 다른 장르도 전부."
--  · search_genres: 장르 → 게임 이름 조각(정규화). 배운 게임 목록(search_games) 기준으로 큐레이션 + 흔한 게임들.
--  · search_intents 'genre': 장르어. 동의어(공겜→공포, 격겜→격투, 시뮬→시뮬레이션…)는 search_synonyms seed-genre.
--  · search_public: 질의(또는 토큰)가 장르어/동의어면 genre_intent — 제목·태그·챕터·코너·게임명이 그 장르 게임 조각과 맞는
--    일정·다시보기·챕터가 정확 결과(hit_genre, matched_on 'genre'). '게임·겜' 같은 군더더기 토큰은 'noise' 의도로 무시.
-- 멱등. 적용: node scripts/apply-db.mjs db/migrations/0094_public_search_genres.sql

-- 장르 → 게임 이름 조각(정규화: 소문자·공백 제거) — 검색어가 장르(또는 그 동의어)면 이 조각이 제목·챕터·게임명에 있는 방송이 잡힌다.
create table if not exists public.search_genres (
  genre text not null,
  game_re text not null,
  primary key (genre, game_re)
);
alter table public.search_genres enable row level security;
drop policy if exists search_genres_public_read on public.search_genres;
create policy search_genres_public_read on public.search_genres for select using (true);
grant select on public.search_genres to anon, authenticated, service_role;
delete from public.search_genres;
insert into public.search_genres (genre, game_re) values
  ('fps', 'apex'),
  ('fps', 'arma'),
  ('fps', 'callofduty'),
  ('fps', 'cs2'),
  ('fps', 'doom'),
  ('fps', 'halo'),
  ('fps', 'overwatch'),
  ('fps', 'pubg'),
  ('fps', 'r6'),
  ('fps', 'tarkov'),
  ('fps', 'valorant'),
  ('fps', '데스티니'),
  ('fps', '레식'),
  ('fps', '레인보우식스'),
  ('fps', '발로'),
  ('fps', '발로란트'),
  ('fps', '배그'),
  ('fps', '배틀그라운드'),
  ('fps', '서든'),
  ('fps', '서든어택'),
  ('fps', '아르마'),
  ('fps', '에이펙스'),
  ('fps', '오버워치'),
  ('fps', '카운터스트라이크'),
  ('fps', '콜오브듀티'),
  ('fps', '타르코프'),
  ('fps', '헤일로'),
  ('mmorpg', 'ff14'),
  ('mmorpg', 'lostark'),
  ('mmorpg', 'mabinogi'),
  ('mmorpg', 'maplestory'),
  ('mmorpg', 'wow'),
  ('mmorpg', '검은사막'),
  ('mmorpg', '던전앤파이터'),
  ('mmorpg', '던파'),
  ('mmorpg', '로스트아크'),
  ('mmorpg', '로아'),
  ('mmorpg', '리니지'),
  ('mmorpg', '마비노기'),
  ('mmorpg', '메이플'),
  ('mmorpg', '블소'),
  ('mmorpg', '와우'),
  ('mmorpg', '월드오브워크래프트'),
  ('mmorpg', '파판14'),
  ('moba', '5인큐'),
  ('moba', 'dota'),
  ('moba', 'lol'),
  ('moba', '도타'),
  ('moba', '리그오브레전드'),
  ('moba', '이리'),
  ('moba', '이터널리턴'),
  ('moba', '자랭'),
  ('moba', '칼바람'),
  ('moba', '히오스'),
  ('rpg', 'darksouls'),
  ('rpg', 'diablo'),
  ('rpg', 'discoelysium'),
  ('rpg', 'dragonquest'),
  ('rpg', 'finalfantasy'),
  ('rpg', 'hades'),
  ('rpg', 'kingdomhearts'),
  ('rpg', 'mabinogi'),
  ('rpg', 'maplestory'),
  ('rpg', 'octopath'),
  ('rpg', 'persona'),
  ('rpg', 'poe'),
  ('rpg', 'pokemon'),
  ('rpg', 'stardew'),
  ('rpg', 'undertale'),
  ('rpg', 'wow'),
  ('rpg', '니케'),
  ('rpg', '다크소울'),
  ('rpg', '드래곤퀘스트'),
  ('rpg', '디스코엘리시움'),
  ('rpg', '디아블로'),
  ('rpg', '로스트아크'),
  ('rpg', '로아'),
  ('rpg', '마비노기'),
  ('rpg', '메이플'),
  ('rpg', '메타포'),
  ('rpg', '명일방주'),
  ('rpg', '명조'),
  ('rpg', '발더스게이트'),
  ('rpg', '블루아카'),
  ('rpg', '사이버펑크'),
  ('rpg', '스카이림'),
  ('rpg', '스타듀밸리'),
  ('rpg', '언더테일'),
  ('rpg', '엘든링'),
  ('rpg', '옥토패스'),
  ('rpg', '와우'),
  ('rpg', '원신'),
  ('rpg', '월드오브워크래프트'),
  ('rpg', '위쳐'),
  ('rpg', '유니콘오버로드'),
  ('rpg', '젤다'),
  ('rpg', '킹덤하츠'),
  ('rpg', '파이널판타지'),
  ('rpg', '패스오브엑자일'),
  ('rpg', '페르소나'),
  ('rpg', '포켓몬'),
  ('rpg', '하데스'),
  ('vr', 'alyx'),
  ('vr', 'beatsaber'),
  ('vr', 'jobsimulator'),
  ('vr', 'superhot'),
  ('vr', 'vr'),
  ('vr', 'vrchat'),
  ('vr', 'vr챗'),
  ('vr', '겟투워크'),
  ('vr', '브이알'),
  ('vr', '비트세이버'),
  ('vr', '슈퍼핫'),
  ('vr', '아카데미정기합방'),
  ('vr', '잡시뮬레이터'),
  ('vr', '최강버튜버'),
  ('vr', '하프라이프알릭스'),
  ('격투', 'blazblue'),
  ('격투', 'guiltygear'),
  ('격투', 'kof'),
  ('격투', 'mortalkombat'),
  ('격투', 'smash'),
  ('격투', 'streetfighter'),
  ('격투', 'tekken'),
  ('격투', '길티기어'),
  ('격투', '대난투'),
  ('격투', '멀티버서스'),
  ('격투', '모탈컴뱃'),
  ('격투', '블레이블루'),
  ('격투', '스매시'),
  ('격투', '스트리트파이터'),
  ('격투', '철권'),
  ('격투', '킹오브'),
  ('공포', '8번출구'),
  ('공포', 'amnesia'),
  ('공포', 'backrooms'),
  ('공포', 'darkwater'),
  ('공포', 'exit8'),
  ('공포', 'fivenights'),
  ('공포', 'fnaf'),
  ('공포', 'lethalcompany'),
  ('공포', 'outlast'),
  ('공포', 'poppyplaytime'),
  ('공포', 'silenthill'),
  ('공포', 'spookys'),
  ('공포', 'theexit8'),
  ('공포', 'zomboid'),
  ('공포', '공포'),
  ('공포', '귀신'),
  ('공포', '노공략벨로나'),
  ('공포', '다크워터'),
  ('공포', '데드바이데이라이트'),
  ('공포', '데드스페이스'),
  ('공포', '데바데'),
  ('공포', '데스티니'),
  ('공포', '레이어스오브피어'),
  ('공포', '레지던트이블'),
  ('공포', '리썰컴퍼니'),
  ('공포', '리틀나이트메어'),
  ('공포', '바이오하자드'),
  ('공포', '반디스나치'),
  ('공포', '방탈출'),
  ('공포', '백룸'),
  ('공포', '사일런트힐'),
  ('공포', '아웃라스트'),
  ('공포', '암네시아'),
  ('공포', '좀보이드'),
  ('공포', '치킨호러'),
  ('공포', '파스모포비아'),
  ('공포', '포피플레이타임'),
  ('공포', '프레디'),
  ('공포', '호러'),
  ('농장', 'animalcrossing'),
  ('농장', 'coralisland'),
  ('농장', 'farmingsimulator'),
  ('농장', 'farmtogether'),
  ('농장', 'harvestmoon'),
  ('농장', 'runefactory'),
  ('농장', 'stardew'),
  ('농장', 'storyofseasons'),
  ('농장', '동물의숲'),
  ('농장', '룬팩토리'),
  ('농장', '모동숲'),
  ('농장', '목장이야기'),
  ('농장', '문라이터'),
  ('농장', '스타듀밸리'),
  ('농장', '코랄아일랜드'),
  ('농장', '파밍시뮬'),
  ('농장', '팜투게더'),
  ('농장', '팰월드'),
  ('농장', '하베스트문'),
  ('덱빌딩', 'balatro'),
  ('덱빌딩', 'cloverpit'),
  ('덱빌딩', 'hearthstone'),
  ('덱빌딩', 'inscryption'),
  ('덱빌딩', 'masterduel'),
  ('덱빌딩', 'slaythespire'),
  ('덱빌딩', '마스터듀얼'),
  ('덱빌딩', '몬스터트레인'),
  ('덱빌딩', '발라트로'),
  ('덱빌딩', '슬더스'),
  ('덱빌딩', '슬레이더스파이어'),
  ('덱빌딩', '유희왕'),
  ('덱빌딩', '인스크립션'),
  ('덱빌딩', '클로버핏'),
  ('덱빌딩', '하스스톤'),
  ('레이싱', 'forza'),
  ('레이싱', 'granturismo'),
  ('레이싱', 'iracing'),
  ('레이싱', 'kartrider'),
  ('레이싱', 'mariokart'),
  ('레이싱', 'needforspeed'),
  ('레이싱', 'trackmania'),
  ('레이싱', '그란투리스모'),
  ('레이싱', '니드포스피드'),
  ('레이싱', '레이싱'),
  ('레이싱', '마리오카트'),
  ('레이싱', '카러플'),
  ('레이싱', '카트라이더'),
  ('레이싱', '트랙매니아'),
  ('레이싱', '포르자'),
  ('로그라이크', 'balatro'),
  ('로그라이크', 'cloverpit'),
  ('로그라이크', 'cultofthelamb'),
  ('로그라이크', 'deadcells'),
  ('로그라이크', 'gungeon'),
  ('로그라이크', 'hades'),
  ('로그라이크', 'inscryption'),
  ('로그라이크', 'isaac'),
  ('로그라이크', 'noita'),
  ('로그라이크', 'riskofrain'),
  ('로그라이크', 'slaythespire'),
  ('로그라이크', 'vampiresurvivors'),
  ('로그라이크', '노이타'),
  ('로그라이크', '데드셀'),
  ('로그라이크', '리스크오브레인'),
  ('로그라이크', '몬스터트레인'),
  ('로그라이크', '발라트로'),
  ('로그라이크', '뱀서'),
  ('로그라이크', '뱀파이어서바이버'),
  ('로그라이크', '슬더스'),
  ('로그라이크', '슬레이더스파이어'),
  ('로그라이크', '아이작'),
  ('로그라이크', '엔터더건전'),
  ('로그라이크', '인스크립션'),
  ('로그라이크', '컬트오브더램'),
  ('로그라이크', '클로버핏'),
  ('로그라이크', '하데스'),
  ('리듬', 'adanceoffireandice'),
  ('리듬', 'beatsaber'),
  ('리듬', 'djmax'),
  ('리듬', 'musedash'),
  ('리듬', 'osu'),
  ('리듬', 'rhythmdoctor'),
  ('리듬', 'rhythmheaven'),
  ('리듬', 'taiko'),
  ('리듬', '디제이맥스'),
  ('리듬', '리듬닥터'),
  ('리듬', '리듬세상'),
  ('리듬', '뮤즈대시'),
  ('리듬', '비트세이버'),
  ('리듬', '사운드볼텍스'),
  ('리듬', '어드밴스워즈'),
  ('리듬', '얼불춤'),
  ('리듬', '프로세카'),
  ('메트로배니아', 'animalwell'),
  ('메트로배니아', 'blasphemous'),
  ('메트로배니아', 'castlevania'),
  ('메트로배니아', 'deadcells'),
  ('메트로배니아', 'hollowknight'),
  ('메트로배니아', 'metroid'),
  ('메트로배니아', 'ninesols'),
  ('메트로배니아', 'ori'),
  ('메트로배니아', 'silksong'),
  ('메트로배니아', '나인솔즈'),
  ('메트로배니아', '데드셀'),
  ('메트로배니아', '메트로이드'),
  ('메트로배니아', '블래스피머스'),
  ('메트로배니아', '실크송'),
  ('메트로배니아', '악마성'),
  ('메트로배니아', '애니멀웰'),
  ('메트로배니아', '할로우나이트'),
  ('메트로이드바니아', 'hollowknight'),
  ('메트로이드바니아', 'silksong'),
  ('메트로이드바니아', '실크송'),
  ('메트로이드바니아', '할로우나이트'),
  ('배틀로얄', 'apex'),
  ('배틀로얄', 'eternalreturn'),
  ('배틀로얄', 'fallguys'),
  ('배틀로얄', 'fortnite'),
  ('배틀로얄', 'pubg'),
  ('배틀로얄', '배그'),
  ('배틀로얄', '배틀그라운드'),
  ('배틀로얄', '에이펙스'),
  ('배틀로얄', '워존'),
  ('배틀로얄', '이리'),
  ('배틀로얄', '이터널리턴'),
  ('배틀로얄', '포트나이트'),
  ('배틀로얄', '폴가이즈'),
  ('샌드박스', 'animalcrossing'),
  ('샌드박스', 'factorio'),
  ('샌드박스', 'minecraft'),
  ('샌드박스', 'rimworld'),
  ('샌드박스', 'roblox'),
  ('샌드박스', 'satisfactory'),
  ('샌드박스', 'sims'),
  ('샌드박스', 'stardew'),
  ('샌드박스', 'terraria'),
  ('샌드박스', 'vrchat'),
  ('샌드박스', 'vr챗'),
  ('샌드박스', '동물의숲'),
  ('샌드박스', '로블록스'),
  ('샌드박스', '림월드'),
  ('샌드박스', '마인크래프트'),
  ('샌드박스', '마크'),
  ('샌드박스', '모동숲'),
  ('샌드박스', '새티스팩토리'),
  ('샌드박스', '스타듀밸리'),
  ('샌드박스', '심즈'),
  ('샌드박스', '테라리아'),
  ('샌드박스', '팩토리오'),
  ('샌드박스', '팰월드'),
  ('생존', 'ark'),
  ('생존', 'dayz'),
  ('생존', 'dontstarve'),
  ('생존', 'minecraft'),
  ('생존', 'palworld'),
  ('생존', 'repo'),
  ('생존', 'rust'),
  ('생존', 'sonsoftheforest'),
  ('생존', 'subnautica'),
  ('생존', 'terraria'),
  ('생존', 'valheim'),
  ('생존', 'zomboid'),
  ('생존', '그린헬'),
  ('생존', '더포레스트'),
  ('생존', '데이즈'),
  ('생존', '돈스타브'),
  ('생존', '러스트'),
  ('생존', '레인월드'),
  ('생존', '레포'),
  ('생존', '롱다크'),
  ('생존', '리썰컴퍼니'),
  ('생존', '마인크래프트'),
  ('생존', '발헤임'),
  ('생존', '서브노티카'),
  ('생존', '선즈오브더포레스트'),
  ('생존', '좀보이드'),
  ('생존', '테라리아'),
  ('생존', '팰월드'),
  ('소울라이크', 'bloodborne'),
  ('소울라이크', 'darksouls'),
  ('소울라이크', 'eldenring'),
  ('소울라이크', 'liesofp'),
  ('소울라이크', 'ninesols'),
  ('소울라이크', 'nioh'),
  ('소울라이크', 'p의거짓'),
  ('소울라이크', 'sekiro'),
  ('소울라이크', 'silksong'),
  ('소울라이크', '나인솔즈'),
  ('소울라이크', '니오'),
  ('소울라이크', '다크소울'),
  ('소울라이크', '라이즈오브더로닌'),
  ('소울라이크', '블래스피머스'),
  ('소울라이크', '블러드본'),
  ('소울라이크', '세키로'),
  ('소울라이크', '실크송'),
  ('소울라이크', '엘든링'),
  ('소울라이크', '할로우나이트'),
  ('슈팅', 'apex'),
  ('슈팅', 'arma'),
  ('슈팅', 'callofduty'),
  ('슈팅', 'cs2'),
  ('슈팅', 'cuphead'),
  ('슈팅', 'destiny'),
  ('슈팅', 'doom'),
  ('슈팅', 'fortnite'),
  ('슈팅', 'halo'),
  ('슈팅', 'overwatch'),
  ('슈팅', 'pubg'),
  ('슈팅', 'r6'),
  ('슈팅', 'splatoon'),
  ('슈팅', 'tarkov'),
  ('슈팅', 'touhou'),
  ('슈팅', 'valorant'),
  ('슈팅', 'vampiresurvivors'),
  ('슈팅', '데스티니'),
  ('슈팅', '동방'),
  ('슈팅', '레식'),
  ('슈팅', '레인보우식스'),
  ('슈팅', '발로'),
  ('슈팅', '발로란트'),
  ('슈팅', '배그'),
  ('슈팅', '배틀그라운드'),
  ('슈팅', '뱀서'),
  ('슈팅', '서든'),
  ('슈팅', '서든어택'),
  ('슈팅', '스플래툰'),
  ('슈팅', '아르마'),
  ('슈팅', '에이펙스'),
  ('슈팅', '오버워치'),
  ('슈팅', '컵헤드'),
  ('슈팅', '콜오브듀티'),
  ('슈팅', '타르코프'),
  ('슈팅', '포트나이트'),
  ('슈팅', '헤일로'),
  ('스포츠', '2k25'),
  ('스포츠', '2k26'),
  ('스포츠', 'efootball'),
  ('스포츠', 'fc24'),
  ('스포츠', 'fc25'),
  ('스포츠', 'fc26'),
  ('스포츠', 'fifa'),
  ('스포츠', 'mlb'),
  ('스포츠', 'nba2k'),
  ('스포츠', '고멤fc'),
  ('스포츠', '골프'),
  ('스포츠', '농구'),
  ('스포츠', '더쇼'),
  ('스포츠', '볼링'),
  ('스포츠', '스포츠'),
  ('스포츠', '야구'),
  ('스포츠', '위닝'),
  ('스포츠', '잔디'),
  ('스포츠', '축구'),
  ('스포츠', '탁구'),
  ('스포츠', '테니스'),
  ('스포츠', '풋볼'),
  ('스포츠', '프로클럽'),
  ('스포츠', '프클'),
  ('스포츠', '피파'),
  ('시뮬레이션', 'animalcrossing'),
  ('시뮬레이션', 'cities'),
  ('시뮬레이션', 'davethediver'),
  ('시뮬레이션', 'eurotruck'),
  ('시뮬레이션', 'factorio'),
  ('시뮬레이션', 'farmingsimulator'),
  ('시뮬레이션', 'flightsimulator'),
  ('시뮬레이션', 'foodstars'),
  ('시뮬레이션', 'howtofish'),
  ('시뮬레이션', 'iracing'),
  ('시뮬레이션', 'octodad'),
  ('시뮬레이션', 'powerwash'),
  ('시뮬레이션', 'rimworld'),
  ('시뮬레이션', 'satisfactory'),
  ('시뮬레이션', 'simcity'),
  ('시뮬레이션', 'sims'),
  ('시뮬레이션', 'stardew'),
  ('시뮬레이션', 'supermarketsimulator'),
  ('시뮬레이션', '데이브더다이버'),
  ('시뮬레이션', '동물의숲'),
  ('시뮬레이션', '림월드'),
  ('시뮬레이션', '모동숲'),
  ('시뮬레이션', '문어아빠'),
  ('시뮬레이션', '새티스팩토리'),
  ('시뮬레이션', '슈퍼마켓시뮬'),
  ('시뮬레이션', '스타듀밸리'),
  ('시뮬레이션', '시티즈'),
  ('시뮬레이션', '심시티'),
  ('시뮬레이션', '심즈'),
  ('시뮬레이션', '언패킹'),
  ('시뮬레이션', '유로트럭'),
  ('시뮬레이션', '이용약관에동의하고싶어'),
  ('시뮬레이션', '파밍시뮬'),
  ('시뮬레이션', '파워워시'),
  ('시뮬레이션', '팩토리오'),
  ('시뮬레이션', '푸드스타즈'),
  ('시뮬레이션', '플라이트시뮬'),
  ('시뮬레이션', '하우스플리퍼'),
  ('어드벤처', 'davethediver'),
  ('어드벤처', 'horizon'),
  ('어드벤처', 'inside'),
  ('어드벤처', 'katamari'),
  ('어드벤처', 'lastofus'),
  ('어드벤처', 'limbo'),
  ('어드벤처', 'pikmin'),
  ('어드벤처', 'pokemon'),
  ('어드벤처', 'stanleyparable'),
  ('어드벤처', 'tombraider'),
  ('어드벤처', 'uncharted'),
  ('어드벤처', 'undertale'),
  ('어드벤처', 'zelda'),
  ('어드벤처', '고스트오브쓰시마'),
  ('어드벤처', '데이브더다이버'),
  ('어드벤처', '라스트오브어스'),
  ('어드벤처', '리틀나이트메어'),
  ('어드벤처', '림보'),
  ('어드벤처', '마리오'),
  ('어드벤처', '슈퍼마리오'),
  ('어드벤처', '스탠리패러블'),
  ('어드벤처', '야숲'),
  ('어드벤처', '언더테일'),
  ('어드벤처', '언차티드'),
  ('어드벤처', '왕눈'),
  ('어드벤처', '인사이드'),
  ('어드벤처', '젤다'),
  ('어드벤처', '젤다의전설'),
  ('어드벤처', '카타마리'),
  ('어드벤처', '툼레이더'),
  ('어드벤처', '포켓몬'),
  ('어드벤처', '피크민'),
  ('어드벤처', '호라이즌'),
  ('오픈월드', 'baldursgate'),
  ('오픈월드', 'cyberpunk'),
  ('오픈월드', 'eldenring'),
  ('오픈월드', 'genshin'),
  ('오픈월드', 'gta'),
  ('오픈월드', 'horizon'),
  ('오픈월드', 'minecraft'),
  ('오픈월드', 'monsterhunter'),
  ('오픈월드', 'palworld'),
  ('오픈월드', 'reddead'),
  ('오픈월드', 'skyrim'),
  ('오픈월드', 'witcher'),
  ('오픈월드', 'zelda'),
  ('오픈월드', '고스트오브쓰시마'),
  ('오픈월드', '레드데드'),
  ('오픈월드', '마인크래프트'),
  ('오픈월드', '명조'),
  ('오픈월드', '몬스터헌터'),
  ('오픈월드', '몬헌'),
  ('오픈월드', '발더스게이트'),
  ('오픈월드', '사이버펑크'),
  ('오픈월드', '스카이림'),
  ('오픈월드', '야숲'),
  ('오픈월드', '엘든링'),
  ('오픈월드', '왕눈'),
  ('오픈월드', '워더링웨이브'),
  ('오픈월드', '원신'),
  ('오픈월드', '위쳐'),
  ('오픈월드', '젤다'),
  ('오픈월드', '좀보이드'),
  ('오픈월드', '테라리아'),
  ('오픈월드', '팰월드'),
  ('오픈월드', '호라이즌'),
  ('전략', 'advancewars'),
  ('전략', 'aoe'),
  ('전략', 'chess'),
  ('전략', 'civilization'),
  ('전략', 'factorio'),
  ('전략', 'fireemblem'),
  ('전략', 'intothebreach'),
  ('전략', 'rimworld'),
  ('전략', 'satisfactory'),
  ('전략', 'starcraft'),
  ('전략', 'totalwar'),
  ('전략', 'unicornoverlord'),
  ('전략', 'warcraft3'),
  ('전략', 'xcom'),
  ('전략', '림월드'),
  ('전략', '문명'),
  ('전략', '새티스팩토리'),
  ('전략', '스타크래프트'),
  ('전략', '슬더스'),
  ('전략', '슬레이더스파이어'),
  ('전략', '어드밴스워즈'),
  ('전략', '에이지오브엠파이어'),
  ('전략', '엑스컴'),
  ('전략', '워크래프트3'),
  ('전략', '유니콘오버로드'),
  ('전략', '인투더브리치'),
  ('전략', '체스'),
  ('전략', '클래시로얄'),
  ('전략', '토탈워'),
  ('전략', '파이어엠블렘'),
  ('전략', '팩토리오'),
  ('추리', 'aceattorney'),
  ('추리', 'amongus'),
  ('추리', 'danganronpa'),
  ('추리', 'discoelysium'),
  ('추리', 'goldenidol'),
  ('추리', 'goosegooseduck'),
  ('추리', 'herstory'),
  ('추리', 'noresultsfound'),
  ('추리', 'obradinn'),
  ('추리', '구스구스덕'),
  ('추리', '노결과'),
  ('추리', '단간론파'),
  ('추리', '디스코엘리시움'),
  ('추리', '라이어게임'),
  ('추리', '리턴오브오브라딘'),
  ('추리', '마피아'),
  ('추리', '스탠리패러블'),
  ('추리', '어몽어스'),
  ('추리', '역전재판'),
  ('추리', '예스노탐정'),
  ('추리', '추리'),
  ('추리', '케이스오브더골든아이돌'),
  ('추리', '탐정'),
  ('추리', '피닉스라이트'),
  ('추리', '회사원'),
  ('축구', 'efootball'),
  ('축구', 'fc24'),
  ('축구', 'fc25'),
  ('축구', 'fc26'),
  ('축구', 'fifa'),
  ('축구', '고멤fc'),
  ('축구', '벽골내기'),
  ('축구', '위닝'),
  ('축구', '잔디'),
  ('축구', '축구'),
  ('축구', '풋볼'),
  ('축구', '프로클럽'),
  ('축구', '프클'),
  ('축구', '피파'),
  ('카드', 'balatro'),
  ('카드', 'cloverpit'),
  ('카드', 'hearthstone'),
  ('카드', 'masterduel'),
  ('카드', 'shadowverse'),
  ('카드', '레전드오브룬테라'),
  ('카드', '룬테라'),
  ('카드', '마스터듀얼'),
  ('카드', '발라트로'),
  ('카드', '섀도우버스'),
  ('카드', '슬더스'),
  ('카드', '슬레이더스파이어'),
  ('카드', '유희왕'),
  ('카드', '인스크립션'),
  ('카드', '포켓몬카드'),
  ('카드', '포켓카'),
  ('카드', '하스스톤'),
  ('코옵', '8번출구'),
  ('코옵', 'amongus'),
  ('코옵', 'backrooms'),
  ('코옵', 'fallguys'),
  ('코옵', 'garticphone'),
  ('코옵', 'goosegooseduck'),
  ('코옵', 'humanfallflat'),
  ('코옵', 'ittakestwo'),
  ('코옵', 'lethalcompany'),
  ('코옵', 'overcooked'),
  ('코옵', 'palworld'),
  ('코옵', 'picopark'),
  ('코옵', 'repo'),
  ('코옵', 'splitfiction'),
  ('코옵', 'terraria'),
  ('코옵', '갈틱폰'),
  ('코옵', '구스구스덕'),
  ('코옵', '레포'),
  ('코옵', '리썰컴퍼니'),
  ('코옵', '백룸'),
  ('코옵', '스플릿픽션'),
  ('코옵', '어몽어스'),
  ('코옵', '오버쿡드'),
  ('코옵', '잇테이크투'),
  ('코옵', '치킨호러'),
  ('코옵', '테라리아'),
  ('코옵', '파스모포비아'),
  ('코옵', '팰월드'),
  ('코옵', '폴가이즈'),
  ('코옵', '피코파크'),
  ('코옵', '휴먼폴플랫'),
  ('탐정', 'aceattorney'),
  ('탐정', 'danganronpa'),
  ('탐정', 'discoelysium'),
  ('탐정', 'goldenidol'),
  ('탐정', 'obradinn'),
  ('탐정', '단간론파'),
  ('탐정', '디스코엘리시움'),
  ('탐정', '리턴오브오브라딘'),
  ('탐정', '역전재판'),
  ('탐정', '예스노탐정'),
  ('탐정', '추리'),
  ('탐정', '케이스오브더골든아이돌'),
  ('탐정', '탐정'),
  ('탐정', '피닉스라이트'),
  ('파티', 'amongus'),
  ('파티', 'fallguys'),
  ('파티', 'foodstars'),
  ('파티', 'gartic'),
  ('파티', 'garticphone'),
  ('파티', 'goosegooseduck'),
  ('파티', 'humanfallflat'),
  ('파티', 'jackbox'),
  ('파티', 'marioparty'),
  ('파티', 'pratfall'),
  ('파티', '갈틱폰'),
  ('파티', '겟투워크'),
  ('파티', '구스구스덕'),
  ('파티', '라이어게임'),
  ('파티', '마리오파티'),
  ('파티', '마추기io'),
  ('파티', '마피아'),
  ('파티', '메챠카멜레온'),
  ('파티', '버블파이터'),
  ('파티', '스위치인생게임'),
  ('파티', '어몽어스'),
  ('파티', '인생게임'),
  ('파티', '잭박스'),
  ('파티', '최강버튜버'),
  ('파티', '친구모아아일랜드'),
  ('파티', '카멜레온'),
  ('파티', '크레이지아케이드'),
  ('파티', '크아'),
  ('파티', '폴가이즈'),
  ('파티', '푸하하'),
  ('파티', '프랫폴'),
  ('파티', '휴먼폴플랫'),
  ('퍼즐', '8번출구'),
  ('퍼즐', 'amongus'),
  ('퍼즐', 'babaisyou'),
  ('퍼즐', 'chants'),
  ('퍼즐', 'goldenidol'),
  ('퍼즐', 'inside'),
  ('퍼즐', 'iq테스트'),
  ('퍼즐', 'katamari'),
  ('퍼즐', 'limbo'),
  ('퍼즐', 'obradinn'),
  ('퍼즐', 'pikmin'),
  ('퍼즐', 'portal'),
  ('퍼즐', 'stanleyparable'),
  ('퍼즐', 'tetris'),
  ('퍼즐', 'theexit8'),
  ('퍼즐', 'unpacking'),
  ('퍼즐', 'witness'),
  ('퍼즐', '구스구스덕'),
  ('퍼즐', '리턴오브오브라딘'),
  ('퍼즐', '리틀나이트메어'),
  ('퍼즐', '림보'),
  ('퍼즐', '바바이즈유'),
  ('퍼즐', '스탠리패러블'),
  ('퍼즐', '어몽어스'),
  ('퍼즐', '언패킹'),
  ('퍼즐', '위트니스'),
  ('퍼즐', '인사이드'),
  ('퍼즐', '카타마리'),
  ('퍼즐', '케이스오브더골든아이돌'),
  ('퍼즐', '테트리스'),
  ('퍼즐', '포탈'),
  ('퍼즐', '포탈2'),
  ('퍼즐', '피크민'),
  ('플랫포머', 'celeste'),
  ('플랫포머', 'cuphead'),
  ('플랫포머', 'gettingoverit'),
  ('플랫포머', 'ghostrunner'),
  ('플랫포머', 'hollowknight'),
  ('플랫포머', 'inside'),
  ('플랫포머', 'jumpking'),
  ('플랫포머', 'limbo'),
  ('플랫포머', 'mario'),
  ('플랫포머', 'onlyup'),
  ('플랫포머', 'ori'),
  ('플랫포머', 'pepper'),
  ('플랫포머', 'rayman'),
  ('플랫포머', 'silksong'),
  ('플랫포머', 'sonic'),
  ('플랫포머', '겟팅오버잇'),
  ('플랫포머', '고스트러너'),
  ('플랫포머', '레이맨'),
  ('플랫포머', '림보'),
  ('플랫포머', '마리오'),
  ('플랫포머', '셀레스테'),
  ('플랫포머', '소닉'),
  ('플랫포머', '슈퍼마리오'),
  ('플랫포머', '실크송'),
  ('플랫포머', '온리업'),
  ('플랫포머', '인사이드'),
  ('플랫포머', '점프맵'),
  ('플랫포머', '점프킹'),
  ('플랫포머', '카타마리'),
  ('플랫포머', '컵헤드'),
  ('플랫포머', '피프'),
  ('플랫포머', '할로우나이트'),
  ('힐링', 'abzu'),
  ('힐링', 'animalcrossing'),
  ('힐링', 'coralisland'),
  ('힐링', 'davethediver'),
  ('힐링', 'goodjob'),
  ('힐링', 'katamari'),
  ('힐링', 'pikmin'),
  ('힐링', 'pokemon'),
  ('힐링', 'powerwash'),
  ('힐링', 'sakuna'),
  ('힐링', 'slimerancher'),
  ('힐링', 'spiritfarer'),
  ('힐링', 'stardew'),
  ('힐링', 'unpacking'),
  ('힐링', '굿잡'),
  ('힐링', '데이브더다이버'),
  ('힐링', '동물의숲'),
  ('힐링', '모동숲'),
  ('힐링', '스타듀밸리'),
  ('힐링', '스피릿페어러'),
  ('힐링', '슬라임랜처'),
  ('힐링', '아바브'),
  ('힐링', '언패킹'),
  ('힐링', '천수의사쿠나히메'),
  ('힐링', '카타마리'),
  ('힐링', '코랄아일랜드'),
  ('힐링', '파워워시'),
  ('힐링', '포켓몬'),
  ('힐링', '피크민')
on conflict do nothing;
insert into public.search_intents (term, intent) values
  ('공포', 'genre'),
  ('코옵', 'genre'),
  ('오픈월드', 'genre'),
  ('rpg', 'genre'),
  ('mmorpg', 'genre'),
  ('fps', 'genre'),
  ('배틀로얄', 'genre'),
  ('moba', 'genre'),
  ('샌드박스', 'genre'),
  ('생존', 'genre'),
  ('로그라이크', 'genre'),
  ('덱빌딩', 'genre'),
  ('리듬', 'genre'),
  ('퍼즐', 'genre'),
  ('플랫포머', 'genre'),
  ('메트로배니아', 'genre'),
  ('소울라이크', 'genre'),
  ('격투', 'genre'),
  ('파티', 'genre'),
  ('레이싱', 'genre'),
  ('스포츠', 'genre'),
  ('축구', 'genre'),
  ('카드', 'genre'),
  ('시뮬레이션', 'genre'),
  ('농장', 'genre'),
  ('추리', 'genre'),
  ('탐정', 'genre'),
  ('어드벤처', 'genre'),
  ('전략', 'genre'),
  ('힐링', 'genre'),
  ('vr', 'genre'),
  ('메트로이드바니아', 'genre'),
  ('슈팅', 'genre'),
  ('게임', 'noise'),
  ('겜', 'noise'),
  ('게임들', 'noise'),
  ('종류', 'noise'),
  ('장르', 'noise')
on conflict do nothing;
delete from public.search_synonyms where source = 'seed-genre';
insert into public.search_synonyms (term, alt, source, kind) values
  ('1인칭슈팅', 'fps', 'seed-genre', 'syn'),
  ('adventure', '어드벤처', 'seed-genre', 'syn'),
  ('aos', 'moba', 'seed-genre', 'syn'),
  ('battleroyale', '배틀로얄', 'seed-genre', 'syn'),
  ('ccg', '카드', 'seed-genre', 'syn'),
  ('coop', '코옵', 'seed-genre', 'syn'),
  ('cozy', '힐링', 'seed-genre', 'syn'),
  ('deckbuilder', '덱빌딩', 'seed-genre', 'syn'),
  ('detective', '탐정', 'seed-genre', 'syn'),
  ('farming', '농장', 'seed-genre', 'syn'),
  ('fighting', '격투', 'seed-genre', 'syn'),
  ('football', '축구', 'seed-genre', 'syn'),
  ('fps', '1인칭슈팅', 'seed-genre', 'syn'),
  ('fps', 'fps게임', 'seed-genre', 'syn'),
  ('fps', '에프피에스', 'seed-genre', 'syn'),
  ('fps', '총게임', 'seed-genre', 'syn'),
  ('fps', '총겜', 'seed-genre', 'syn'),
  ('fps게임', 'fps', 'seed-genre', 'syn'),
  ('metroidvania', '메트로배니아', 'seed-genre', 'syn'),
  ('mmo', 'mmorpg', 'seed-genre', 'syn'),
  ('mmorpg', 'mmo', 'seed-genre', 'syn'),
  ('mmorpg', '엠엠오', 'seed-genre', 'syn'),
  ('mmorpg', '엠엠오알피지', 'seed-genre', 'syn'),
  ('mmorpg', '온라인rpg', 'seed-genre', 'syn'),
  ('moba', 'aos', 'seed-genre', 'syn'),
  ('moba', '모바', 'seed-genre', 'syn'),
  ('moba', '에이오에스', 'seed-genre', 'syn'),
  ('mystery', '추리', 'seed-genre', 'syn'),
  ('openworld', '오픈월드', 'seed-genre', 'syn'),
  ('partygame', '파티', 'seed-genre', 'syn'),
  ('platformer', '플랫포머', 'seed-genre', 'syn'),
  ('puzzle', '퍼즐', 'seed-genre', 'syn'),
  ('racing', '레이싱', 'seed-genre', 'syn'),
  ('rhythm', '리듬', 'seed-genre', 'syn'),
  ('roguelike', '로그라이크', 'seed-genre', 'syn'),
  ('roguelite', '로그라이크', 'seed-genre', 'syn'),
  ('rpg', 'rpg게임', 'seed-genre', 'syn'),
  ('rpg', '롤플레잉', 'seed-genre', 'syn'),
  ('rpg', '롤플레잉게임', 'seed-genre', 'syn'),
  ('rpg', '알피지', 'seed-genre', 'syn'),
  ('rpg', '알피지게임', 'seed-genre', 'syn'),
  ('rpg게임', 'rpg', 'seed-genre', 'syn'),
  ('rts', '전략', 'seed-genre', 'syn'),
  ('sandbox', '샌드박스', 'seed-genre', 'syn'),
  ('shooter', '슈팅', 'seed-genre', 'syn'),
  ('shooting', '슈팅', 'seed-genre', 'syn'),
  ('simulation', '시뮬레이션', 'seed-genre', 'syn'),
  ('soccer', '축구', 'seed-genre', 'syn'),
  ('soulslike', '소울라이크', 'seed-genre', 'syn'),
  ('sports', '스포츠', 'seed-genre', 'syn'),
  ('strategy', '전략', 'seed-genre', 'syn'),
  ('survival', '생존', 'seed-genre', 'syn'),
  ('tcg', '카드', 'seed-genre', 'syn'),
  ('vr', 'vr게임', 'seed-genre', 'syn'),
  ('vr', '가상현실', 'seed-genre', 'syn'),
  ('vr', '브이알', 'seed-genre', 'syn'),
  ('vr', '브이알게임', 'seed-genre', 'syn'),
  ('vr게임', 'vr', 'seed-genre', 'syn'),
  ('가상현실', 'vr', 'seed-genre', 'syn'),
  ('감성게임', '힐링', 'seed-genre', 'syn'),
  ('같이하는게임', '코옵', 'seed-genre', 'syn'),
  ('격겜', '격투', 'seed-genre', 'syn'),
  ('격투', 'fighting', 'seed-genre', 'syn'),
  ('격투', '격겜', 'seed-genre', 'syn'),
  ('격투', '격투게임', 'seed-genre', 'syn'),
  ('격투', '대전격투', 'seed-genre', 'syn'),
  ('격투게임', '격투', 'seed-genre', 'syn'),
  ('공겜', '공포', 'seed-genre', 'syn'),
  ('공포', '공겜', 'seed-genre', 'syn'),
  ('공포', '공포게임', 'seed-genre', 'syn'),
  ('공포', '공포겜', 'seed-genre', 'syn'),
  ('공포', '무서운거', 'seed-genre', 'syn'),
  ('공포', '무서운게임', 'seed-genre', 'syn'),
  ('공포', '호러', 'seed-genre', 'syn'),
  ('공포', '호러게임', 'seed-genre', 'syn'),
  ('공포게임', '공포', 'seed-genre', 'syn'),
  ('공포겜', '공포', 'seed-genre', 'syn'),
  ('농사', '농장', 'seed-genre', 'syn'),
  ('농사게임', '농장', 'seed-genre', 'syn'),
  ('농장', 'farming', 'seed-genre', 'syn'),
  ('농장', '농사', 'seed-genre', 'syn'),
  ('농장', '농사게임', 'seed-genre', 'syn'),
  ('농장', '농장게임', 'seed-genre', 'syn'),
  ('농장', '농장시뮬', 'seed-genre', 'syn'),
  ('농장게임', '농장', 'seed-genre', 'syn'),
  ('농장시뮬', '농장', 'seed-genre', 'syn'),
  ('단체게임', '파티', 'seed-genre', 'syn'),
  ('대전격투', '격투', 'seed-genre', 'syn'),
  ('덱빌더', '덱빌딩', 'seed-genre', 'syn'),
  ('덱빌딩', 'deckbuilder', 'seed-genre', 'syn'),
  ('덱빌딩', '덱빌더', 'seed-genre', 'syn'),
  ('덱빌딩', '덱빌딩게임', 'seed-genre', 'syn'),
  ('덱빌딩', '덱빌딩로그라이크', 'seed-genre', 'syn'),
  ('덱빌딩게임', '덱빌딩', 'seed-genre', 'syn'),
  ('덱빌딩로그라이크', '덱빌딩', 'seed-genre', 'syn'),
  ('두뇌게임', '퍼즐', 'seed-genre', 'syn'),
  ('레이싱', 'racing', 'seed-genre', 'syn'),
  ('레이싱', '레이싱게임', 'seed-genre', 'syn'),
  ('레이싱', '레이싱겜', 'seed-genre', 'syn'),
  ('레이싱', '카레이싱', 'seed-genre', 'syn'),
  ('레이싱게임', '레이싱', 'seed-genre', 'syn'),
  ('레이싱겜', '레이싱', 'seed-genre', 'syn'),
  ('로그라이크', 'roguelike', 'seed-genre', 'syn'),
  ('로그라이크', 'roguelite', 'seed-genre', 'syn'),
  ('로그라이크', '로그라이트', 'seed-genre', 'syn'),
  ('로그라이크', '로그류', 'seed-genre', 'syn'),
  ('로그라이트', '로그라이크', 'seed-genre', 'syn'),
  ('로그류', '로그라이크', 'seed-genre', 'syn'),
  ('롤플레잉', 'rpg', 'seed-genre', 'syn'),
  ('롤플레잉게임', 'rpg', 'seed-genre', 'syn'),
  ('리듬', 'rhythm', 'seed-genre', 'syn'),
  ('리듬', '리듬게임', 'seed-genre', 'syn'),
  ('리듬', '리듬겜', 'seed-genre', 'syn'),
  ('리듬', '음겜', 'seed-genre', 'syn'),
  ('리듬', '음악게임', 'seed-genre', 'syn'),
  ('리듬게임', '리듬', 'seed-genre', 'syn'),
  ('리듬겜', '리듬', 'seed-genre', 'syn'),
  ('멀티', '코옵', 'seed-genre', 'syn'),
  ('멀티게임', '코옵', 'seed-genre', 'syn'),
  ('메트로배니아', 'metroidvania', 'seed-genre', 'syn'),
  ('메트로배니아', '메트로베니아', 'seed-genre', 'syn'),
  ('메트로배니아', '메트로이드바니아', 'seed-genre', 'syn'),
  ('메트로베니아', '메트로배니아', 'seed-genre', 'syn'),
  ('메트로이드바니아', '메트로배니아', 'seed-genre', 'syn'),
  ('모바', 'moba', 'seed-genre', 'syn'),
  ('모험', '어드벤처', 'seed-genre', 'syn'),
  ('모험게임', '어드벤처', 'seed-genre', 'syn'),
  ('무서운거', '공포', 'seed-genre', 'syn'),
  ('무서운게임', '공포', 'seed-genre', 'syn'),
  ('미스터리', '추리', 'seed-genre', 'syn'),
  ('미스테리', '추리', 'seed-genre', 'syn'),
  ('배로', '배틀로얄', 'seed-genre', 'syn'),
  ('배틀로얄', 'battleroyale', 'seed-genre', 'syn'),
  ('배틀로얄', '배로', 'seed-genre', 'syn'),
  ('배틀로얄', '배틀로얄게임', 'seed-genre', 'syn'),
  ('배틀로얄게임', '배틀로얄', 'seed-genre', 'syn'),
  ('브이알', 'vr', 'seed-genre', 'syn'),
  ('브이알게임', 'vr', 'seed-genre', 'syn'),
  ('샌드박스', 'sandbox', 'seed-genre', 'syn'),
  ('샌드박스', '샌박', 'seed-genre', 'syn'),
  ('샌박', '샌드박스', 'seed-genre', 'syn'),
  ('생존', 'survival', 'seed-genre', 'syn'),
  ('생존', '생존게임', 'seed-genre', 'syn'),
  ('생존', '서바이벌', 'seed-genre', 'syn'),
  ('생존', '서바이벌게임', 'seed-genre', 'syn'),
  ('생존게임', '생존', 'seed-genre', 'syn'),
  ('서바이벌', '생존', 'seed-genre', 'syn'),
  ('서바이벌게임', '생존', 'seed-genre', 'syn'),
  ('소울게임', '소울라이크', 'seed-genre', 'syn'),
  ('소울라이크', 'soulslike', 'seed-genre', 'syn'),
  ('소울라이크', '소울게임', 'seed-genre', 'syn'),
  ('소울라이크', '소울라이크게임', 'seed-genre', 'syn'),
  ('소울라이크', '소울류', 'seed-genre', 'syn'),
  ('소울라이크게임', '소울라이크', 'seed-genre', 'syn'),
  ('소울류', '소울라이크', 'seed-genre', 'syn'),
  ('슈팅', 'shooter', 'seed-genre', 'syn'),
  ('슈팅', 'shooting', 'seed-genre', 'syn'),
  ('슈팅', '슈팅게임', 'seed-genre', 'syn'),
  ('슈팅', '슈팅겜', 'seed-genre', 'syn'),
  ('슈팅게임', '슈팅', 'seed-genre', 'syn'),
  ('슈팅겜', '슈팅', 'seed-genre', 'syn'),
  ('스포츠', 'sports', 'seed-genre', 'syn'),
  ('스포츠', '스포츠게임', 'seed-genre', 'syn'),
  ('스포츠', '스포츠겜', 'seed-genre', 'syn'),
  ('스포츠게임', '스포츠', 'seed-genre', 'syn'),
  ('스포츠겜', '스포츠', 'seed-genre', 'syn'),
  ('시뮬', '시뮬레이션', 'seed-genre', 'syn'),
  ('시뮬게임', '시뮬레이션', 'seed-genre', 'syn'),
  ('시뮬레이션', 'simulation', 'seed-genre', 'syn'),
  ('시뮬레이션', '시뮬', 'seed-genre', 'syn'),
  ('시뮬레이션', '시뮬게임', 'seed-genre', 'syn'),
  ('시뮬레이션', '시뮬레이션게임', 'seed-genre', 'syn'),
  ('시뮬레이션게임', '시뮬레이션', 'seed-genre', 'syn'),
  ('알피지', 'rpg', 'seed-genre', 'syn'),
  ('알피지게임', 'rpg', 'seed-genre', 'syn'),
  ('액션어드벤처', '어드벤처', 'seed-genre', 'syn'),
  ('어드벤처', 'adventure', 'seed-genre', 'syn'),
  ('어드벤처', '모험', 'seed-genre', 'syn'),
  ('어드벤처', '모험게임', 'seed-genre', 'syn'),
  ('어드벤처', '액션어드벤처', 'seed-genre', 'syn'),
  ('어드벤처', '어드벤처게임', 'seed-genre', 'syn'),
  ('어드벤처게임', '어드벤처', 'seed-genre', 'syn'),
  ('에이오에스', 'moba', 'seed-genre', 'syn'),
  ('에프피에스', 'fps', 'seed-genre', 'syn'),
  ('엠엠오', 'mmorpg', 'seed-genre', 'syn'),
  ('엠엠오알피지', 'mmorpg', 'seed-genre', 'syn'),
  ('오픈월드', 'openworld', 'seed-genre', 'syn'),
  ('오픈월드', '오픈월드게임', 'seed-genre', 'syn'),
  ('오픈월드게임', '오픈월드', 'seed-genre', 'syn'),
  ('온라인rpg', 'mmorpg', 'seed-genre', 'syn'),
  ('음겜', '리듬', 'seed-genre', 'syn'),
  ('음악게임', '리듬', 'seed-genre', 'syn'),
  ('잔잔한게임', '힐링', 'seed-genre', 'syn'),
  ('전략', 'rts', 'seed-genre', 'syn'),
  ('전략', 'strategy', 'seed-genre', 'syn'),
  ('전략', '전략게임', 'seed-genre', 'syn'),
  ('전략', '전략겜', 'seed-genre', 'syn'),
  ('전략', '턴제', 'seed-genre', 'syn'),
  ('전략', '턴제전략', 'seed-genre', 'syn'),
  ('전략게임', '전략', 'seed-genre', 'syn'),
  ('전략겜', '전략', 'seed-genre', 'syn'),
  ('점프게임', '플랫포머', 'seed-genre', 'syn'),
  ('총게임', 'fps', 'seed-genre', 'syn'),
  ('총겜', 'fps', 'seed-genre', 'syn'),
  ('추리', 'mystery', 'seed-genre', 'syn'),
  ('추리', '미스터리', 'seed-genre', 'syn'),
  ('추리', '미스테리', 'seed-genre', 'syn'),
  ('추리', '추리게임', 'seed-genre', 'syn'),
  ('추리', '추리겜', 'seed-genre', 'syn'),
  ('추리게임', '추리', 'seed-genre', 'syn'),
  ('추리겜', '추리', 'seed-genre', 'syn'),
  ('축겜', '축구', 'seed-genre', 'syn'),
  ('축구', 'football', 'seed-genre', 'syn'),
  ('축구', 'soccer', 'seed-genre', 'syn'),
  ('축구', '축겜', 'seed-genre', 'syn'),
  ('축구', '축구게임', 'seed-genre', 'syn'),
  ('축구', '축구겜', 'seed-genre', 'syn'),
  ('축구게임', '축구', 'seed-genre', 'syn'),
  ('축구겜', '축구', 'seed-genre', 'syn'),
  ('카드', 'ccg', 'seed-genre', 'syn'),
  ('카드', 'tcg', 'seed-genre', 'syn'),
  ('카드', '카드게임', 'seed-genre', 'syn'),
  ('카드', '카드겜', 'seed-genre', 'syn'),
  ('카드', '카드배틀', 'seed-genre', 'syn'),
  ('카드게임', '카드', 'seed-genre', 'syn'),
  ('카드겜', '카드', 'seed-genre', 'syn'),
  ('카드배틀', '카드', 'seed-genre', 'syn'),
  ('카레이싱', '레이싱', 'seed-genre', 'syn'),
  ('코옵', 'coop', 'seed-genre', 'syn'),
  ('코옵', '같이하는게임', 'seed-genre', 'syn'),
  ('코옵', '멀티', 'seed-genre', 'syn'),
  ('코옵', '멀티게임', 'seed-genre', 'syn'),
  ('코옵', '코옵게임', 'seed-genre', 'syn'),
  ('코옵', '협동', 'seed-genre', 'syn'),
  ('코옵', '협동게임', 'seed-genre', 'syn'),
  ('코옵게임', '코옵', 'seed-genre', 'syn'),
  ('코지게임', '힐링', 'seed-genre', 'syn'),
  ('탐정', 'detective', 'seed-genre', 'syn'),
  ('탐정', '탐정게임', 'seed-genre', 'syn'),
  ('탐정', '탐정겜', 'seed-genre', 'syn'),
  ('탐정게임', '탐정', 'seed-genre', 'syn'),
  ('탐정겜', '탐정', 'seed-genre', 'syn'),
  ('턴제', '전략', 'seed-genre', 'syn'),
  ('턴제전략', '전략', 'seed-genre', 'syn'),
  ('파티', 'partygame', 'seed-genre', 'syn'),
  ('파티', '단체게임', 'seed-genre', 'syn'),
  ('파티', '파티게임', 'seed-genre', 'syn'),
  ('파티', '파티겜', 'seed-genre', 'syn'),
  ('파티게임', '파티', 'seed-genre', 'syn'),
  ('파티겜', '파티', 'seed-genre', 'syn'),
  ('퍼즐', 'puzzle', 'seed-genre', 'syn'),
  ('퍼즐', '두뇌게임', 'seed-genre', 'syn'),
  ('퍼즐', '퍼즐게임', 'seed-genre', 'syn'),
  ('퍼즐', '퍼즐겜', 'seed-genre', 'syn'),
  ('퍼즐게임', '퍼즐', 'seed-genre', 'syn'),
  ('퍼즐겜', '퍼즐', 'seed-genre', 'syn'),
  ('플랫포머', 'platformer', 'seed-genre', 'syn'),
  ('플랫포머', '점프게임', 'seed-genre', 'syn'),
  ('플랫포머', '플랫포밍', 'seed-genre', 'syn'),
  ('플랫포머', '플랫폼게임', 'seed-genre', 'syn'),
  ('플랫포밍', '플랫포머', 'seed-genre', 'syn'),
  ('플랫폼게임', '플랫포머', 'seed-genre', 'syn'),
  ('협동', '코옵', 'seed-genre', 'syn'),
  ('협동게임', '코옵', 'seed-genre', 'syn'),
  ('호러', '공포', 'seed-genre', 'syn'),
  ('호러게임', '공포', 'seed-genre', 'syn'),
  ('힐링', 'cozy', 'seed-genre', 'syn'),
  ('힐링', '감성게임', 'seed-genre', 'syn'),
  ('힐링', '잔잔한게임', 'seed-genre', 'syn'),
  ('힐링', '코지게임', 'seed-genre', 'syn'),
  ('힐링', '힐링게임', 'seed-genre', 'syn'),
  ('힐링', '힐링겜', 'seed-genre', 'syn'),
  ('힐링게임', '힐링', 'seed-genre', 'syn'),
  ('힐링겜', '힐링', 'seed-genre', 'syn')
on conflict (term, alt) do nothing;

drop function if exists public.search_public(uuid, text, integer);
create function public.search_public(p_calendar_id uuid, p_q text, p_limit integer default 50)
returns table (
  kind text,
  event_id uuid,
  title_no bigint,
  sec integer,
  date_key date,
  start_time time,
  title text,
  snippet text,
  duration_ms bigint,
  host_nick text,
  thumb text,
  score numeric,
  exact boolean,
  popularity numeric,
  section text,
  parent text,
  matched_on text,
  corrected text
)
language sql
stable
security definer
set search_path = public
as $$
  with qc as materialized (
    -- 오타 교정(0086/0087): 질의가 사전에 없으면 가장 가까운 사전어로. 초성·한 글자·다단어는 교정 안 함.
    select
      public.search_norm(p_q) as qn0,
      case
        when public.search_norm(p_q) ~ '^[ㄱ-ㅎ]+$' or length(public.search_norm(p_q)) < 2 or p_q ~ '\s' then null
        when exists (select 1 from public.search_synonyms s where s.term = public.search_norm(p_q))
          or exists (select 1 from public.search_intents i where i.term = public.search_norm(p_q))
          or exists (select 1 from public.search_entities e where e.name = public.search_norm(p_q))
          or exists (select 1 from public.search_games g where g.norm = public.search_norm(p_q)) then null
        else public.search_correct(public.search_norm(p_q))
      end as corr
  ),
  q0 as (
    select
      coalesce(qc.corr, qc.qn0) as qn,
      qc.corr as corrected,
      coalesce(qc.corr, qc.qn0) ~ '^[ㄱ-ㅎ]+$' as is_cho,
      (length(coalesce(qc.corr, qc.qn0)) >= 2
        or exists (select 1 from public.search_synonyms s where s.term = coalesce(qc.corr, qc.qn0))) as min_ok,
      case when qc.corr is not null then array[qc.corr] else array_remove(array(
        select public.search_norm(t) from regexp_split_to_table(coalesce(p_q, ''), '\s+') as t
        where length(public.search_norm(t)) >= 2
           or exists (select 1 from public.search_synonyms s where s.term = public.search_norm(t))
      ), '') end as toks
    from qc
  ),
  q1 as (
    select
      q0.qn, q0.is_cho, q0.toks, q0.min_ok, q0.corrected,
      case when q0.is_cho then array[q0.qn]
           when length(q0.qn) = 1 then array(select s.alt from public.search_synonyms s where s.term = q0.qn and s.kind = 'syn')
           else array_prepend(q0.qn, array(select s.alt from public.search_synonyms s where s.term = q0.qn and s.kind = 'syn')) end as alts,
      case when q0.is_cho then array[]::text[]
           else array(select s.alt from public.search_synonyms s where s.term = q0.qn and s.kind = 'rel') end as rels,
      case when q0.is_cho then q0.toks
           else array(
             select t.tok || coalesce('|' || string_agg(s.alt, '|'), '')
             from unnest(q0.toks) with ordinality as t(tok, ord)
             left join public.search_synonyms s on s.term = t.tok and s.kind = 'syn'
             group by t.tok, t.ord order by t.ord
           ) end as tokg,
      (not q0.is_cho and (
        exists (select 1 from public.search_intents i where i.intent = 'song' and (i.term = q0.qn or i.term = any(q0.toks)))
        or exists (select 1 from public.search_intents i join public.search_synonyms s on s.alt = i.term and s.kind = 'syn' where i.intent = 'song' and s.term = q0.qn)
      )) as song_intent,
      (not q0.is_cho and exists (select 1 from public.search_intents i where i.intent = 'dance' and (i.term = q0.qn or i.term = any(q0.toks)))) as dance_intent,
      (not q0.is_cho and exists (select 1 from public.search_intents i where i.intent = 'hum' and (i.term = q0.qn or i.term = any(q0.toks)))) as hum_intent,
      (not q0.is_cho and exists (select 1 from public.search_intents i where i.intent = 'minor_game' and (i.term = q0.qn or i.term = any(q0.toks)))) as game_intent,
      array(select t from unnest(q0.toks) t where not exists (
        select 1 from public.search_intents i
        where i.term = t or exists (select 1 from public.search_synonyms s where s.term = t and s.alt = i.term and s.kind = 'syn')
      )) as rest_toks,
      -- 장르 의도(0094): 질의(또는 토큰)가 장르어(공포·코옵·오픈월드·rpg…)이거나 그 동의어(공겜→공포)면 그 장르들.
      case when q0.is_cho then array[]::text[] else array(
        select distinct i.term from public.search_intents i
        where i.intent = 'genre' and (
          i.term = q0.qn or i.term = any(q0.toks)
          or exists (select 1 from public.search_synonyms s where s.alt = i.term and s.kind = 'syn' and (s.term = q0.qn or s.term = any(q0.toks)))
        )
      ) end as genre_terms
    from q0
  ),
  genre_games as (
    -- 그 장르에 속한 게임 이름 조각들의 정규식(정규화 문자열 위에서 부분 일치). 없으면 null.
    select case when count(*) = 0 then null else '(' || string_agg(g.game_re, '|') || ')' end as re
    from public.search_genres g, q1
    where g.genre = any(q1.genre_terms)
  ),
  games as (
    select '(' || string_agg(regexp_replace(g.norm, '([.^$|()\[\]{}*+?\\])', '\\\1', 'g'), '|') || ')' as re
    from public.search_games g where g.kind = 'minor' and length(g.norm) >= 3
  ),
  ev as (
    select
      e.id, e.date_key, e.start_time, e.public_title,
      coalesce(e.public_description, '') as descr,
      public.search_norm(e.public_title) as tn,
      public.search_norm(e.public_description) as dn,
      lower(e.public_title) as traw,
      lower(coalesce(e.public_description, '')) as draw,
      lower(coalesce((
        select string_agg(bt.display_name, ' ')
        from public.event_tags et join public.broadcast_tags bt on bt.id = et.tag_id
        where et.event_id = e.id
      ), '')) as graw,
      public.search_norm(coalesce((
        select string_agg(bt.display_name, ' ')
        from public.event_tags et join public.broadcast_tags bt on bt.id = et.tag_id
        where et.event_id = e.id
      ), '')) as tagn
    from public.events e
    where e.calendar_id = p_calendar_id
      and e.deleted_at is null
      and e.visibility_scope = 'public'
      and e.status <> 'draft'
      and not (coalesce(e.teaser, false) and e.teaser_reveal_at is not null and e.teaser_reveal_at > now())
  ),
  vods as (
    select
      v.title_no, v.broadcast_day, v.title, v.duration_ms, v.host_nick, v.thumb,
      v.read_cnt, v.like_cnt, v.comment_cnt,
      public.search_norm(v.title) as tn,
      coalesce(t.entry_count, 0) as entry_count
    from public.vod_archive v
    left join public.vod_timeline t on t.title_no = v.title_no
    where v.auth_no = 101
  ),
  corpus as (
    select case when q.is_cho then public.search_choseong(ev.tn || ev.tagn || ev.dn) else ev.tn || ev.tagn || ev.dn end as norm
    from ev, q1 q
    union all
    select case when q.is_cho then public.search_choseong(v.tn) else v.tn end from vods v, q1 q
    union all
    select case when q.is_cho then c.label_cho else c.label_norm || '|' || c.section_norm || '|' || c.parent_norm end from public.vod_chapter_index c, q1 q
  ),
  q as (
    select
      q1.qn, q1.is_cho, q1.alts, q1.tokg as toks, q1.min_ok, q1.corrected, q1.song_intent, q1.dance_intent, q1.hum_intent, q1.game_intent, q1.rest_toks,
      (cardinality(q1.genre_terms) > 0) as genre_intent,
      (select re from genre_games) as gre2,
      case when cardinality(q1.alts) = 0 then '(?!)' else '(' || array_to_string(q1.alts, '|') || ')' end as qre,
      case when cardinality(q1.rels) = 0 then null else '(' || array_to_string(q1.rels, '|') || ')' end as qrel,
      case when cardinality(q1.rest_toks) = 0 then null else '(' || array_to_string(q1.rest_toks, '|') || ')' end as qrest,
      (select re from games) as gre,
      -- 두 글자 한글 질의(사전 확장 없음)는 정규화(띄어쓰기 제거) 문자열이 아니라 **원문**에서 붙어 있어야 적중
      -- (0091, 소유자: "이게"가 "이 게임"에 걸렸다). 사전어(메·롤 확장, 배그)는 alts가 2개 이상이라 제외.
      (not q1.is_cho and q1.corrected is null and length(q1.qn) = 2 and cardinality(q1.alts) = 1 and q1.qn ~ '^[가-힣]+$') as short2,
      lower(trim(coalesce(p_q, ''))) as qraw,
      (not q1.is_cho and length(q1.qn) between 2 and 4) as abbrev_on,
      '%' || substr(q1.qn, 1, 1) || '%' || substr(q1.qn, length(q1.qn), 1) || '%' as ablike,
      array(
        select (ln(((select count(*) from corpus) + 1.0) / ((select count(*) from corpus where corpus.norm ~ ('(' || t.tok || ')')) + 1.0)) + 1)::numeric
        from unnest(q1.tokg) with ordinality as t(tok, ord)
        order by t.ord
      ) as tokw,
      cardinality(q1.toks) as ntok
    from q1
  ),
  ev_hearts as (
    select h.event_id, count(*)::numeric as n
    from (select event_id from public.event_hearts union all select event_id from public.event_hearts_anon) h
    group by h.event_id
  ),
  ev_max as (select greatest(1, coalesce(max(n), 1)) as mx from ev_hearts),
  evm as (
    select ev.*,
      case when q.is_cho then public.search_choseong(ev.tn) else ev.tn end as tnm,
      case when q.is_cho then public.search_choseong(ev.dn) else ev.dn end as dnm,
      case when q.is_cho then public.search_choseong(ev.tagn) else ev.tagn end as tagnm,
      ((case when q.is_cho then public.search_choseong(ev.tn) else ev.tn end) ~ q.qre and (not q.short2 or ev.traw like '%' || q.qraw || '%')) as hit_t,
      ((case when q.is_cho then public.search_choseong(ev.tagn) else ev.tagn end) ~ q.qre and (not q.short2 or ev.graw like '%' || q.qraw || '%')) as hit_g,
      ((case when q.is_cho then public.search_choseong(ev.dn) else ev.dn end) ~ q.qre and (not q.short2 or ev.draw like '%' || q.qraw || '%')) as hit_d,
      (q.qrel is not null and (ev.tn || ev.tagn || ev.dn) ~ q.qrel) as hit_r,
      (q.game_intent and q.gre is not null and ev.tn ~ q.gre and not public.search_game_is_major(ev.tn)
        and (q.qrest is null or (ev.tn || ev.tagn) ~ q.qrest)) as hit_game,
      (case when not q.abbrev_on or ev.tn !~~ q.ablike or (ev.tn ~ q.qre) then false
            else public.search_abbrev_match(q.qn, ev.public_title) end) as hit_ab,
      (q.genre_intent and q.gre2 is not null and (ev.tn || ev.tagn) ~ q.gre2
        and (q.qrest is null or (ev.tn || ev.tagn) ~ q.qrest)) as hit_genre,
      coalesce((select n from ev_hearts where ev_hearts.event_id = ev.id), 0) / (select mx from ev_max) as pop
    from ev, q
  ),
  ev_scored as (
    select
      'event'::text as kind, ev.id as event_id, null::bigint as title_no, null::integer as sec,
      ev.date_key, ev.start_time, ev.public_title as title,
      case
        when not q.is_cho and hit_d and position(lower(trim(coalesce(p_q, ''))) in lower(ev.descr)) > 0 then
          substr(ev.descr, greatest(1, position(lower(trim(coalesce(p_q, ''))) in lower(ev.descr)) - 30), 120)
        when hit_d then substr(ev.descr, 1, 120)
        else ''
      end as snippet,
      null::bigint as duration_ms, null::text as host_nick, null::text as thumb,
      (
        greatest(3.0 * similarity(ev.tnm, q.qn), 1.2 * similarity(ev.tagnm, q.qn), 0.7 * similarity(ev.dnm, q.qn))
        + case
            when hit_game then 2.6
            when hit_genre then 2.2
            when hit_t then 1.2
            when hit_g or hit_d then 0.6
            when q.ntok > 1 and public.search_tok_ratio(ev.tnm || ev.tagnm || ev.dnm, q.toks, q.tokw) > 0
              then 1.0 * public.search_tok_ratio(ev.tnm || ev.tagnm || ev.dnm, q.toks, q.tokw)
            when hit_r then 0.5
            when hit_ab then 0.4
            else 0
          end
        + 0.4 * pop
        + 0.3 * exp(-greatest(0, (current_date - ev.date_key))::numeric / 365.0)
      )::numeric as score,
      (hit_game or hit_genre or hit_t or hit_g or hit_d or hit_r or (q.ntok > 1 and public.search_tok_ratio(ev.tnm || ev.tagnm || ev.dnm, q.toks, q.tokw) > 0)) as exact,
      pop::numeric as popularity,
      ''::text as section, ''::text as parent,
      case when hit_game then 'game' when hit_genre then 'genre' when hit_t then 'title' when hit_g then 'tag' when hit_d then 'description' when q.ntok > 1 and public.search_tok_ratio(ev.tnm || ev.tagnm || ev.dnm, q.toks, q.tokw) > 0 then 'tokens' when hit_r then 'related' when hit_ab then 'abbrev' else 'fuzzy' end as matched_on,
      coalesce(q.corrected, '') as corrected
    from evm ev, q
    where q.min_ok and (
      hit_game or hit_genre or hit_t or hit_g or hit_d or hit_r or hit_ab
      or (q.ntok > 1 and public.search_tok_ratio(ev.tnm || ev.tagnm || ev.dnm, q.toks, q.tokw) > 0)
      or (length(q.qn) >= 2 and similarity(ev.tnm, q.qn) >= 0.25)
    )
  ),
  vod_max as (
    select greatest(1, coalesce(max(read_cnt), 1))::numeric as mx_read,
           greatest(1, coalesce(max(like_cnt + comment_cnt), 1))::numeric as mx_react,
           greatest(1, coalesce(max(entry_count), 1))::numeric as mx_ch
    from vods
  ),
  vod_engage as (
    select v.title_no,
      0.4 * ln(1 + v.read_cnt) / ln(1 + m.mx_read)
      + 0.2 * ln(1 + v.like_cnt + v.comment_cnt) / ln(1 + m.mx_react)
      + 0.2 * v.entry_count / m.mx_ch as engagement,
      0.3 * exp(-greatest(0, (current_date - v.broadcast_day))::numeric / 365.0) as freshness
    from vods v, vod_max m
  ),
  vodm as (
    select v.*,
      case when q.is_cho then public.search_choseong(v.tn) else v.tn end as tnm,
      ((case when q.is_cho then public.search_choseong(v.tn) else v.tn end) ~ q.qre and (not q.short2 or lower(v.title) like '%' || q.qraw || '%')) as hit_t,
      (q.qrel is not null and v.tn ~ q.qrel) as hit_r,
      (q.game_intent and (
        (q.gre is not null and v.tn ~ q.gre)
        or exists (select 1 from public.vod_chapter_index c join public.search_games g on g.norm = c.game_norm where c.title_no = v.title_no and g.kind = 'minor')
      ) and (q.qrest is null or v.tn ~ q.qrest)) as hit_game,
      (case when not q.abbrev_on or v.tn !~~ q.ablike or (v.tn ~ q.qre) then false
            else public.search_abbrev_match(q.qn, v.title) end) as hit_ab,
      (q.genre_intent and q.gre2 is not null and (
        v.tn ~ q.gre2
        or exists (select 1 from public.vod_chapter_index c where c.title_no = v.title_no and (c.game_norm || '|' || c.section_norm) ~ q.gre2)
      ) and (q.qrest is null or v.tn ~ q.qrest)) as hit_genre
    from vods v, q
  ),
  vod_scored as (
    select
      'vod'::text as kind, null::uuid as event_id, v.title_no, null::integer as sec,
      v.broadcast_day as date_key, null::time as start_time, v.title, ''::text as snippet,
      v.duration_ms, nullif(v.host_nick, '') as host_nick, v.thumb,
      (
        2.0 * similarity(v.tnm, q.qn)
        + case
            when hit_game then 2.8
            when hit_genre then 2.3
            when hit_t then 1.2
            when q.ntok > 1 and public.search_tok_ratio(v.tnm, q.toks, q.tokw) > 0 then 1.0 * public.search_tok_ratio(v.tnm, q.toks, q.tokw)
            when hit_r then 0.5
            when hit_ab then 0.4
            else 0
          end
        + g.engagement + g.freshness
      )::numeric as score,
      (hit_game or hit_genre or hit_t or hit_r or (q.ntok > 1 and public.search_tok_ratio(v.tnm, q.toks, q.tokw) > 0)) as exact,
      (g.engagement / 0.8)::numeric as popularity,
      ''::text as section, ''::text as parent,
      case when hit_game then 'game' when hit_genre then 'genre' when hit_t then 'title' when q.ntok > 1 and public.search_tok_ratio(v.tnm, q.toks, q.tokw) > 0 then 'tokens' when hit_r then 'related' when hit_ab then 'abbrev' else 'fuzzy' end as matched_on,
      coalesce(q.corrected, '') as corrected
    from vodm v
    join vod_engage g on g.title_no = v.title_no, q
    where q.min_ok and (
      hit_game or hit_genre or hit_t or hit_r or hit_ab
      or (q.ntok > 1 and public.search_tok_ratio(v.tnm, q.toks, q.tokw) > 0)
      or (length(q.qn) >= 2 and similarity(v.tnm, q.qn) >= 0.25)
    )
  ),
  chm as (
    select c.title_no, c.sec, c.label, c.section, c.parent, c.song_kind,
      case when q.is_cho then c.label_cho else c.label_norm end as cm,
      c.label_norm || '|' || c.section_norm || '|' || c.parent_norm as cmx,
      ((case when q.is_cho then c.label_cho else c.label_norm end) ~ q.qre and (not q.short2 or lower(c.label) like '%' || q.qraw || '%')) as hit_t,
      (not q.is_cho and (c.section_norm || '|' || c.parent_norm) ~ q.qre and (not q.short2 or lower(c.section || '|' || c.parent) like '%' || q.qraw || '%')) as hit_s,
      (q.qrel is not null and (c.label_norm || '|' || c.section_norm || '|' || c.parent_norm) ~ q.qrel) as hit_r,
      (q.qrest is null or (c.label_norm || '|' || c.section_norm) ~ q.qrest) as rest_ok,
      (q.song_intent and c.song_kind = 'sung') as hit_song,
      (q.song_intent and c.song_kind = 'listen') as hit_listen,
      ((q.song_intent or q.hum_intent) and c.song_kind = 'hum') as hit_hum,
      (q.dance_intent and c.song_kind = 'dance') as hit_dance,
      (q.game_intent and c.is_section_start and c.game_norm <> ''
        and exists (select 1 from public.search_games g where g.norm = c.game_norm and g.kind = 'minor')) as hit_game,
      (case when not q.abbrev_on or c.label_norm !~~ q.ablike or (c.label_norm ~ q.qre) then false
            else public.search_abbrev_match(q.qn, c.label) end) as hit_ab,
      (q.genre_intent and q.gre2 is not null and (c.label_norm || '|' || c.section_norm || '|' || c.game_norm) ~ q.gre2) as hit_genre
    from public.vod_chapter_index c, q
  ),
  ch_scored as (
    select
      'chapter'::text as kind, null::uuid as event_id, c.title_no, c.sec,
      v.broadcast_day as date_key, null::time as start_time, c.label as title, v.title as snippet,
      v.duration_ms, nullif(v.host_nick, '') as host_nick, v.thumb,
      (
        1.5 * similarity(c.cm, q.qn)
        + case
            when c.rest_ok and c.hit_game then 2.4
            when c.rest_ok and c.hit_genre then 2.0
            when c.rest_ok and c.hit_song then 2.8
            when c.rest_ok and c.hit_dance then 2.8
            when c.rest_ok and c.hit_hum and q.hum_intent then 2.8
            when c.hit_t then 1.2
            when c.rest_ok and c.hit_hum then 1.0
            when c.hit_s then 0.9
            when c.rest_ok and c.hit_listen then 0.8
            when q.ntok > 1 and public.search_tok_ratio(c.cmx, q.toks, q.tokw) > 0 then 1.0 * public.search_tok_ratio(c.cmx, q.toks, q.tokw)
            when c.hit_r then 0.5
            when c.hit_ab then 0.4
            else 0
          end
        + g.engagement + g.freshness
      )::numeric as score,
      ((c.rest_ok and (c.hit_game or c.hit_genre or c.hit_song or c.hit_dance or c.hit_hum or c.hit_listen)) or c.hit_t or c.hit_s or c.hit_r or (q.ntok > 1 and public.search_tok_ratio(c.cmx, q.toks, q.tokw) >= 0.5)) as exact,
      (g.engagement / 0.8)::numeric as popularity,
      c.section, c.parent,
      case
        when c.rest_ok and c.hit_game then 'game'
        when c.rest_ok and c.hit_genre then 'genre'
        when c.rest_ok and c.hit_song then 'song'
        when c.rest_ok and c.hit_dance then 'dance'
        when c.rest_ok and c.hit_hum then 'hum'
        when c.hit_t then 'label'
        when c.hit_s then 'section'
        when c.rest_ok and c.hit_listen then 'listen'
        when q.ntok > 1 and public.search_tok_ratio(c.cmx, q.toks, q.tokw) > 0 then 'tokens'
        when c.hit_r then 'related' when c.hit_ab then 'abbrev' else 'fuzzy' end as matched_on,
      coalesce(q.corrected, '') as corrected
    from chm c
    join vods v on v.title_no = c.title_no
    join vod_engage g on g.title_no = c.title_no, q
    where q.min_ok and (
      (c.rest_ok and (c.hit_game or c.hit_genre or c.hit_song or c.hit_dance or c.hit_hum or c.hit_listen))
      or c.hit_t or c.hit_s or c.hit_r or c.hit_ab
      or (q.ntok > 1 and public.search_tok_ratio(c.cmx, q.toks, q.tokw) >= 0.5)
      or (length(q.qn) >= 2 and not q.short2 and similarity(c.cm, q.qn) >= 0.3)
    )
  ),
  -- 채팅 반응 적중(0093): 시청자 채팅에서 그 말이 많이 나온 방송 → 가장 몰린 30초 구간으로 가는 챕터 모양 행.
  -- 단어 전체가 질의(또는 동의어)와 같을 때만("이게"가 "이게임" 안에 걸리지 않게), 방송당 5회 이상.
  -- 팬 챕터가 이미 같은 말을 잡은 방송은 뺀다(같은 방송이 두 번 나오지 않게). 원문은 없다 — 단어·구간뿐.
  chat_scored as (
    select
      'chapter'::text as kind, null::uuid as event_id, t.title_no, (coalesce(t.peak_bin, 0) * 30)::integer as sec,
      v.broadcast_day as date_key, null::time as start_time,
      ('채팅 "' || t.term || '" 반응 구간')::text as title, v.title as snippet,
      v.duration_ms, nullif(v.host_nick, '') as host_nick, v.thumb,
      (0.9 + least(1.0, ln(1 + t.cnt) / 5.0) + g.engagement + g.freshness)::numeric as score,
      (t.cnt >= 10) as exact,
      (g.engagement / 0.8)::numeric as popularity,
      '채팅'::text as section, ''::text as parent,
      'chat'::text as matched_on,
      coalesce(q.corrected, '') as corrected
    from public.vod_chat_terms t
    join vods v on v.title_no = t.title_no
    join vod_engage g on g.title_no = t.title_no, q
    where q.min_ok and not q.is_cho and t.cnt >= 5 and t.peak_bin is not null
      and t.term ~ ('^' || q.qre || '$')
      and not exists (select 1 from chm c where c.title_no = t.title_no and (c.hit_t or c.hit_s))
      and not exists (select 1 from vodm x where x.title_no = t.title_no and x.hit_t)
  ),
  merged as (
    select * from ev_scored union all select * from vod_scored union all select * from ch_scored union all select * from chat_scored
  )
  select kind, event_id, title_no, sec, date_key, start_time, title, snippet, duration_ms, host_nick, thumb,
         round(score, 4) as score, exact, round(popularity, 4) as popularity, section, parent, matched_on, corrected
  from merged
  order by exact desc, score desc, date_key desc, sec asc nulls first
  limit greatest(1, least(coalesce(p_limit, 50), 400));
$$;
comment on function public.search_public(uuid, text, integer) is
  '시청자 검색(0076~0094) — 오타 교정(자모 편집거리) + 공연 종류·종겜 의도·챕터 코너·동의어/관련어/줄임말/IDF/초성. 공개 데이터만.';
grant execute on function public.search_public(uuid, text, integer) to anon, authenticated;

